version: "3"

services:
    nginx:
        image: nginx:1.13-alpine
        ports:
            - 80:80
        volumes:
            - .:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        image: php:7.0-fpm
        volumes:
            - .:/usr/share/nginx/html

    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=web
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.6
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
